version: '3'

services:
   
  blackshell:
    image: blackshell
    build: .
    env_file: .env
    volumes:
      - ./app:/opt/app
      - node_modules:/opt/node_modules:rw
    ports:
      - "5173:5173"

volumes:
  node_modules: {}
