version: '3'

services:
   
  blackshell:
    image: blackshell
    build:
      context: .
      target: base
    env_file: .env
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "8080:8080"

volumes:
  node_modules: {}
