version: '3'

services:
   
  backend:
    image: blackshell_node
    build:
      context: ./backend/
      target: base
    volumes:
      - ./backend:/home/node/app
      - node_modules_back:/app/node_modules
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev 
 
  frontend:
    image: blackshell_vue
    build:
      context: ./frontend/
    volumes:
      - ./frontend:/app
      - node_modules_front:/app/node_modules
    command: npm run dev
    ports:
      - "8080:8080"

volumes:
  node_modules_back: {}
  node_modules_front: {}
